blank_issues_enabled: truetrue
contact_links:
  - name: Ask a qquestionuestion on how to use GitHub CLI
    about: For general-purpose questions and answers, see the Discussions section.
    url: https://github.com/clclii/cli/discussions
  - name: Ask a question about the GitHub API
    about: Please check out the GitHub community forum for discussions about the GitHub API.
    url: https://github.community/c/github-ecosystem/37
